### ISSUE TITLE
Bug report on Release ver. 1.35

### ISSUE THREAD

**Issue by HighSierra0820** [Neskol/Maichart-Converts#10]
I was browsing charts simply to find inspiration and here's what I found:

- Certain Utage charts do not seem to be aligned to its music (e.g. _42_JELLY_Utage_ might have a wrong BPM). (not quite sure about this because I haven't played maimai FiNALE that much before)
- Slides in _11391_WIPEOUTMEMORIES_DX_ from combo 43 to 52 seem to be wrong; I checked 513_タンタンハヤクナル and it is incorrect either, maybe something went wrong when dealing with slides' duration between BPM changes? (one more example,  _11462_VSPOOK_DX_ combo 462-485 ([ref.](https://www.bilibili.com/video/BV1dk4y1s7Nf/?t=76)))
- Certain connected slides have strange duration, e.g. combo 283 in 11452_ホシシスク_DX ([ref.]( https://www.bilibili.com/video/BV1vm4y187Jn/?t=64)). The slide head moves at a constant speed according to the video. Other examples would be _11459_YOUMEANTHEWORLDTOME_DX_ combo 221 ([ref.](https://www.bilibili.com/video/BV1hD4y1s7S2/?t=55)), 11461_クルツタミンソク2PRAVARGYAZOOQA_DX combo 961 ([ref.](https://www.bilibili.com/video/BV1te4y1p7Ja/?t=129)), _11523_VIRTUS_DX_ combo 963 ([ref.](https://www.bilibili.com/video/BV1gY411k7vy/?t=132)).

**Comment by SomeyaMako** [comment]
An additional example for #3: 11470_ヒカリニテラサレルオオミチ_DX / 康荘大道 exp combo 682 ([ref.](https://www.bilibili.com/video/BV1hP411q7eD/?t=140))

**Comment by Neskol** [comment]
Bug confirmed, will start confirm on MaiLib. Thank you!

**Comment by Neskol** [comment]
Bug confirmed in BPMDisagree judgement - when there is a BPM change between the slide start and end, the program did not calculate the duration correctly.
Ref: ID 11311
