### ISSUE TITLE
Upload to Releases

### ISSUE THREAD

**Issue by Zucker-jex** [Neskol/Maichart-Converts#13]
这一次的更新并没有上传到“Releases”，而是“Mega”。并不知道有什么原因。
我分叉了仓库并上传到了“[Releases](https://github.com/Zucker-jex/Maichart-Converts/releases/tag/ALL)”
Ps：密码在passwd.txt中

This update was not uploaded to "Releases", but to "Mega". I don't know why.
I forked the warehouse and uploaded it to "[Releases](https://github.com/Zucker-jex/Maichart-Converts/releases/tag/ALL)"
Ps: The password is in passwd.txt

**Comment by Neskol** [comment]
我重新上传到了mega中，如果您有时间的话还请再补档一份。谢谢！
I have reuploaded to mega with v1.45, please upload it again if you got time, thanks!

[v1.45](https://github.com/Neskol/Maichart-Converts/releases/tag/v1.45_1.0.7.1)
