### ISSUE TITLE
最新版MEGA链接炸了

### ISSUE THREAD

**Issue by Jun024545** [Neskol/Maichart-Converts#15]
最新版[MEGA](https://[mega.nz/folder/cXxSDCqZ#wQ-VPHywFRX0M-YEUhKZfQ](https://mega.nz/folder/cXxSDCqZ#wQ-VPHywFRX0M-YEUhKZfQ))链接下载不了，并显示这个：
![Snipaste_2024-07-30_19-51-32](https://github.com/user-attachments/assets/21439301-7318-4b29-bfb7-0af0a713e361)

**Comment by Jun024545** [comment]
作者大大可以解决一下吗？

**Comment by Neskol** [comment]
重新上传了 [v1.45](https://github.com/Neskol/Maichart-Converts/releases/tag/v1.45_1.0.7.1)
