### ISSUE TITLE
Upload to Releases

### ISSUE THREAD

**Issue by Zucker-jex** [Neskol/Maichart-Converts#18]
我分叉了仓库并上传到了“[Releases](https://github.com/Zucker-jex/Maichart-Converts/releases/)”
HEVC BGA部分的将上传至OneDrive
I forked the warehouse and uploaded it to "[Releases](https://github.com/Zucker-jex/Maichart-Converts/releases/)"
The HEVC BGA part will be uploaded to OneDrive

[1.45](https://github.com/Zucker-jex/Maichart-Converts/releases/tag/240915)

**Comment by Neskol** [comment]
非常感谢您的帮助！
Thank you so much for your reupload!

**Comment by armv7a** [comment]
请问还有更新的意愿吗

**Comment by Zucker-jex** [comment]
If you'd like, [here](jex.zucker@outlook.com) is my email.
